### ISSUE TITLE
document nightly for macros or?

### ISSUE THREAD

**Issue by jacobrosenthal** [fudanchii/imtomu-rs#14]
Looks like were still nightly because of proc_macros use of #![feature(proc_macro_diagnostic)]

obviously can make examples not use macros.. I saw this issue though, can we ship most of that functionality using this?

https://internals.rust-lang.org/t/custom-error-diagnostics-with-procedural-macros-on-almost-stable-rust/8113

**Comment by fudanchii** [comment]
this seems doable, I'll try experimenting with this :+1: 

thanks!
