### ISSUE TITLE
2018 Edition udpate

### ISSUE THREAD

**Issue by jacobrosenthal** [fudanchii/imtomu-rs#16]
Any reason not to move to 2018 edition? The crate pathing would really clean up some refactors Im trying to do. Mainly Im worried about the rtc branch getting tough to handle. We could either merge it or deal with it later

**Comment by fudanchii** [comment]
Let's go for it.

I can't really find the chance to update, as I currently busy with day job which somehow doesn't relate to Rust or embedded stuff at all.

No worries about rtc branch.
